### ISSUE TITLE
翻译方式问题

### ISSUE THREAD

**Issue by camike** [whatwg-cn/html#21]
请问，我们可不可以保留英文原本，在每段文本上，以tip形式展示译文（类似于划词翻译）？

这样可以专心翻译而不必关心html链接。

**Comment by harttle** [comment]
> 可以专心翻译而不必关心html链接。

这确实是一直想解决的问题，可以大幅降低门槛。但是一直没啥好办法。

**Comment by wangzishi** [comment]
> > 可以专心翻译而不必关心html链接。
> 
> 这确实是一直想解决的问题，可以大幅降低门槛。但是一直没啥好办法。

我一直觉得Angular文档翻译的方式很好，点击译文即可查看原文，是否可以参考？
中文文档：https://angular.cn/docs
中文仓库：https://github.com/angular/angular-cn
