### ISSUE TITLE
英文源码和网站对不上

### ISSUE THREAD

**Issue by bige-cyz** [whatwg-cn/html#30]
比如
1.9 Structure of this specification的Loading web pages
HTML documents do not exist in a vacuum — this section defines many of the features that affect environments that deal with multiple pages, such as web browsers.
仓库源码是
HTML documents do not exist in a vacuum &mdash; this section defines many of the features that affect environments that deal with multiple pages, such as web browsers and offline caching of web applications.

**Comment by harttle** [comment]
确保仓库 clean 并可以 build 通过后，用 `make update-en` 可以更新英文源码。注意：它只会更新未翻译过的那部分，大概率会导致一些 ref 对应不上，build 会有很多错误需要修复，比如 update 过程中：

- 有些定义在英文中的 id 会消失，导致已翻译的中文对它们的引用失效，需要（参照它们对应的新原文）移除或更新这些引用点。
- 有些新增的英文会引用新的 id，已翻译的中文并未定义，也需要更新已翻译的文本增加这些 id 的定义。

这里有更多关于 buid 的文档：https://github.com/whatwg-cn/html/wiki/%E6%9E%84%E5%BB%BA%E8%BF%87%E7%A8%8B#%E6%9E%84%E5%BB%BA%E5%B7%A5%E5%85%B7
