### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by Clovin** [whatwg-cn/html#9]
3.2.5.2 内容的种类 这一小节

> 章节内容，标题内容，短语内容，嵌入内容和交互式内容都是流式内容。元数据有时也是流失内容。 元数据和交互式内容有时是短语内容。嵌入内容也是短语内容，有时也是交互式内容。

“元数据有时也是流失内容”这一句的“流失内容”错误，应改为“流式内容”。

**Comment by harttle** [comment]
有兴趣发 PR 不，顺便把你的名字更新到 README.md 的贡献列表

**Comment by Clovin** [comment]
哈哈哈，好的，有兴趣，谢谢。

**Comment by harttle** [comment]
感谢 @Clovin 。已修复，见 #10
